[package]
name = "cairo_button"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flemish = "0.4"
cairo-rs = "0.18"
cairo-blur = "^0.1"
