[package]
name = "rmp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flemish = "0.5"
serde = { version="1.0", features = ["derive"] }
rmp-serde = { version="1.1" }
