[package]
name = "cairo_frame"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flemish = { path = "../../" }
fltk = { version = "^1.4", features = ["use-ninja", "cairoext"] }
cairo-rs = "0.18"
