[workspace]

resolver = "2"
members = [
    "cairo",
    "cairo_shadow_button",
    "calculator",
    "csv",
    "fltodo",
    "flightbooker",
    "resters",
]

[profile.release]
strip = true
opt-level = "z"
lto = true
panic = "abort"
