pub use fltk::dialog::alert;
pub use fltk::dialog::alert_default;
pub use fltk::dialog::choice2 as choice;
pub use fltk::dialog::choice2_default as choice_default;
pub use fltk::dialog::input;
pub use fltk::dialog::input_default;
pub use fltk::dialog::message;
pub use fltk::dialog::message_default;
pub use fltk::dialog::message_title;
pub use fltk::dialog::message_title_default;
pub use fltk::dialog::password;
pub use fltk::dialog::password_default;
pub use fltk::dialog::NativeFileChooser;
pub use fltk::dialog::NativeFileChooserAction;
pub use fltk::dialog::NativeFileChooserOptions;
pub use fltk::dialog::NativeFileChooserType;
